name: cd pipeline (GitOps sync)

on:
  workflow_run:
    workflows: ["ci pipeline"]     
    types:
      - completed

jobs:
  update-gitops:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: NghiaNT05/goldenowl-devops-internship-deploy
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops   

      - name: Update image tag in deployment.yaml
        run: |
          cd gitops/apps/devops-demo
          sed -i "s|image: .*|image: nghiant2005/devops-demo:${{ github.event.workflow_run.head_sha }}|" deployment.yaml

      - name: Commit and push changes
        run: |
          cd gitops
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update image tag to ${{ github.event.workflow_run.head_sha }}" || echo "No changes to commit"
          git push origin master
